pub const MAXIMUM_SIGNERS: usize = 32;
pub const DEFAULT_WARMUP_COOLDOWN_RATE: f64 = 0.25;
pub const FEATURE_STAKE_RAISE_MINIMUM_DELEGATION_TO_1_SOL: bool = false;
pub const LAMPORTS_PER_SOL: u64 = 1_000_000_000;
pub const NEW_WARMUP_COOLDOWN_RATE: f64 = 0.09;
